# APRENDENDO PANDAS

In [2]:
import pandas as pd

In [3]:
alunos = {'Nome':['Ricardo','Pedro','Roberto','Carlos'],
         'Nota':[4,7,5.5,9],
         'Aprovado':['Nao','Sim','Nao','Sim']}


In [4]:
dataframe = pd.DataFrame(alunos) #transformando dicionario em dataframe

In [5]:
print(dataframe) #transforma em uma tabela com indices

      Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2  Roberto   5.5      Nao
3   Carlos   9.0      Sim


In [ ]:
#o Series transforma tanto listas quanto arrays em Series, mas precisam ser unidimenssionais

In [7]:
objeto1 = pd.Series([2,6,9,10,5]) #comando Series cria um array unidimenssional com indices
print(objeto1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [12]:
import numpy as np
array1 =np.array([2,6,9,10,5])
array2 = np.array([(2,6,9,10,5),(3,4,5,6,7)]) #ele pode criar um array bidimenssioal
print(array1)
print(array2)

[ 2  6  9 10  5]
[[ 2  6  9 10  5]
 [ 3  4  5  6  7]]


In [14]:
objeto2 = pd.Series(array1) #transforma um array na serie 
print(objeto2) 

0     2
1     6
2     9
3    10
4     5
dtype: int32


In [15]:
alunosDIC = {'Nome':['Ricardo','Pedro','Roberto','Carlos'],
         'Nota':[4,7,5.5,9],
         'Aprovado':['Nao','Sim','Nao','Sim']}


In [16]:
alunosDF = pd.DataFrame(alunosDIC)

In [17]:
print(alunosDF)

      Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2  Roberto   5.5      Nao
3   Carlos   9.0      Sim


In [18]:
alunosDF.head() #cabeçalho

Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2  Roberto   5.5      Nao
3   Carlos   9.0      Sim

In [19]:
alunosDF.shape #quantas linhas e colunas

(4, 3)

In [24]:
alunosDF.describe() #traz insformacoes estatisticas

Nota
count  4.000000
mean   6.375000
std    2.136001
min    4.000000
25%    5.125000
50%    6.250000
75%    7.500000
max    9.000000

# filtros de linhas e colunas

In [25]:
alunosDF['Nota']

0    4.0
1    7.0
2    5.5
3    9.0
Name: Nota, dtype: float64

In [26]:
alunosDF['Nome']

0    Ricardo
1      Pedro
2    Roberto
3     Carlos
Name: Nome, dtype: object

In [28]:
alunosDF.loc[[0,2]] #traz a linha do indice 0

Nome  Nota Aprovado
0  Ricardo   4.0      Nao
2  Roberto   5.5      Nao

In [30]:
alunosDF.loc[0:2] #traz a linha do indice 0

Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2  Roberto   5.5      Nao

In [31]:
alunosDF.loc[alunosDF['Nome']=='Pedro'] #filtrando pelo PEDRO

Nome  Nota Aprovado
1  Pedro   7.0      Sim

# MALIPULANDO LINHAS

In [32]:
primeiraslinhas = alunosDF.loc[0:2] #vai receber as 1o linhas

In [33]:
print(primeiraslinhas)

      Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2  Roberto   5.5      Nao


In [37]:
novoDF = alunosDF.loc[alunosDF['Nota']!=9] 

In [38]:
print(novoDF)

      Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2  Roberto   5.5      Nao


In [39]:
alunosReprovados = alunosDF.loc[alunosDF['Aprovado']!='Sim'] 

In [40]:
print(alunosReprovados)

      Nome  Nota Aprovado
0  Ricardo   4.0      Nao
2  Roberto   5.5      Nao
