# FUNÇOES E LAMBDA
    

In [3]:
def somaQuadrado(a,b):
    somaQ= a**2 + b**2
    return somaQ

In [4]:
somaQuadrado(2,3)

13

In [5]:
somaQuadrado2 = lambda a,b :  a**2 + b**2

In [6]:
somaQuadrado2(2,3)

13

 # FUNCAO MAP

In [12]:
kmh = [40,50,56,64,73,79,85,96,100,120]

In [13]:
#convertendo para milhas/hora
#opcao 1
mph = []
for i in kmh:
    mph.append(i/1.61)
print(mph)

[24.844720496894407, 31.05590062111801, 34.78260869565217, 39.75155279503105, 45.3416149068323, 49.06832298136646, 52.795031055900616, 59.62732919254658, 62.11180124223602, 74.53416149068323]


In [15]:
mph2 = list(map(lambda x: x/1.61,kmh)) #map = funcao, quais dados vai ser aplicado a funcao
#depois precisa transformar map em qual type a gente quer, por isso o list na frente
print(mph2)

[24.844720496894407, 31.05590062111801, 34.78260869565217, 39.75155279503105, 45.3416149068323, 49.06832298136646, 52.795031055900616, 59.62732919254658, 62.11180124223602, 74.53416149068323]


# list Comprehension

In [16]:
mph3 = [x/1.61 for x in kmh] #aplica a equacao para cada elemebto da lista
print(mph3)

[24.844720496894407, 31.05590062111801, 34.78260869565217, 39.75155279503105, 45.3416149068323, 49.06832298136646, 52.795031055900616, 59.62732919254658, 62.11180124223602, 74.53416149068323]


In [17]:
caracteres = [i for i in 'Ditádica Tech']

In [18]:
print(caracteres)

['D', 'i', 't', 'á', 'd', 'i', 'c', 'a', ' ', 'T', 'e', 'c', 'h']


# PACOTE NUMPY

In [38]:
import numpy as np

In [39]:
#array é uma lista com restricoes, todos elementos precisam ser do mesmo tipo
a = np.array([1,2,3])


In [40]:
print(a)

[1 2 3]


In [41]:
b = np.array([(2,5,7),(5,3,9),(4,6,5)])

In [42]:
print(b)

[[2 5 7]
 [5 3 9]
 [4 6 5]]


In [43]:
c = np.zeros((4,3)) #matriz de 4 linhas 3 colunas
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
d = np.ones((4,3)) #matriz de 4 linhas 3 colunas
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [45]:
e = np.eye((4)) #matriz de 4 linhas 3 colunas
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [46]:
b.max() #funcao dentro da matriz b

9

In [48]:
b.min() #funcao dentro da matriz b

2

In [49]:
b.mean() #media

5.111111111111111

In [50]:
b.std() #devio padrao

1.9688939051854832

In [52]:
b.sum() #devio padrao

46

# ABRINDO ARQUIVOS

In [2]:
import pandas as pd
dados = pd.read_excel('C:/Users/RG944SA/Desktop/curso-AnaliseDados/arquivo1.xlsx') #precisa alterar as barras

In [3]:
dados.head(6) #ele traz uma coluna de indice

Números Letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e
5        6      f

In [4]:
dados2 = pd.read_csv('C:/Users/RG944SA/Desktop/curso-AnaliseDados/athlete_events.csv')

In [6]:
dados2.head(5)

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN